apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-0l1p
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-0l1p
    app.kubernetes.io/part-of: tkrw-pr714-0075-0068-app
  name: devfile-sample-0l1p
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-0l1p
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-0l1p
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0068-tenant/tkrw-pr714-0075-0068-app/devfile-sample-0l1p@sha256:60180e76fab5a4980faecac919f5e0e6c9160bef27315c0b7bf8e94ccfccc18f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
